### ISSUE TITLE
Wrong Timestamp on Export

### ISSUE THREAD

**Issue by colinatkins** [hunterae/dumpable#1]
I tested this with Ruby 2.4.3 and Rails 5.2.0.

When running dumpable with the following command:
`Dumpable.dump(Model, Model, ..., :file => "#{Rails.root.join('db', 'dump.sql')}")`

A Datetime column is exported as follows:
> 2018-05-15 16:54:54 UTC

However the " UTC" is not allowed when importing back into Mysql.

Please consider the following fix within Dumpable::Dumper
Line 81:
```
      case value.class.to_s
      when "Time"
        "'#{value.strftime("%Y-%m-%d %H:%M:%S")}'"
      when 'ActiveSupport::TimeWithZone'
        "'#{value.strftime("%Y-%m-%d %H:%M:%S")}'"
```

**Comment by hunterae** [comment]
Good suggestion @loyaruarutoitsu . I went ahead and added this and released 0.3.1. Thanks!
